
"""
AgentRun Model - Stores execution history for AI agents
"""
from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Text
from sqlalchemy.orm import relationship
from database import Base
from datetime import datetime


class AgentRun(Base):
    """
    Model for storing AI agent execution results

    Fields:
        id: Unique identifier for the run
        agent_id: Reference to the agent that was executed
        input_prompt: The input provided to the agent
        output_response: The response generated by the AI model
        execution_time: Time taken to execute the agent (in milliseconds)
        created_at: Timestamp when the execution occurred
    """
    __tablename__ = "agent_runs"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)
    prompt_version_id = Column(Integer, ForeignKey("prompt_versions.id"), nullable=True)
    input_prompt = Column(Text, nullable=True)
    output_response = Column(Text, nullable=False)
    execution_time = Column(Integer, nullable=False)  # in milliseconds
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationship to Agent
    agent = relationship("Agent", back_populates="runs")
    # Relationship to Feedback
    feedback = relationship("AgentFeedback", back_populates="agent_run")
