-- Add new columns to agents table
ALTER TABLE agents ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE agents ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE agents ADD COLUMN role VARCHAR;
ALTER TABLE agents ADD COLUMN skills JSON;
