FLOWORA_WATERMARK = "Generated by Flowora — Where AI Agents Flow Together"


def apply_flowora_watermark(output):
    if isinstance(output, str):
        if FLOWORA_WATERMARK in output:
            return output
        trimmed = output.rstrip()
        return f"{trimmed}\n\n{FLOWORA_WATERMARK}" if trimmed else FLOWORA_WATERMARK
    if isinstance(output, dict):
        if "watermark" in output:
            return output
        merged = dict(output)
        merged["watermark"] = FLOWORA_WATERMARK
        return merged
    return output
